version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"
    REGION: "ap-northeast-1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=$(aws ssm get-parameter --name "/codebuild/sample-project-dev-nextjs-repo/uri" --with-decryption --query 'Parameter.Value' --output text --region $REGION)
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd nextjs
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - cd ..
      - echo Tagging the Docker image...
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Generating imagedefinitions.json
      - printf '[{"name":"nextjs-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json


artifacts:
  files:
    - nextjs/appspec.yaml
    - nextjs/taskdef.json
    - imagedefinitions.json
